# Generated by Django 3.1.2 on 2020-11-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20201104_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='ordered_price',
            field=models.FloatField(default=0),
        ),
    ]
