# Generated by Django 3.1.2 on 2020-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201102_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_percent',
            field=models.FloatField(default=0),
        ),
    ]
