# Generated by Django 3.1.2 on 2020-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201102_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='product_ingredients', through='product.ProductIngredient', to='product.Ingredients'),
        ),
    ]
